### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by obestwalter** [denis-zhdanov/intellij-plugin-export-keymap#18]
It is broken a long time now and there is no reaction to the issues. It unsurprisingly is still broken in 2016.1

`the number of constructors during runtime and compile time for com.intellij.openapi.ui.DialogWrapper do not match. Expected 6 but got 7
java.lang.IncompatibleClassChangeError: the number of constructors during runtime and compile time for com.intellij.openapi.ui.DialogWrapper do not match. Expected 6 but got 7
    at groovy.lang.MetaClassImpl.selectConstructorAndTransformArguments(MetaClassImpl.java:1381)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.selectConstructorAndTransformArguments(ScriptBytecodeAdapter.java:234)
    at org.intellij.plugins.export.keymap.ExportKeymapAction$1.<init>(ExportKeymapAction.groovy)
    at org.intellij.plugins.export.keymap.ExportKeymapAction.actionPerformed(ExportKeymapAction.groovy:82)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:191)
    at com.intellij.ide.actions.GotoActionAction$7.run(GotoActionAction.java:275)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by dmimat** [comment]
Starting from Jan 2018, the project is maintained again

**Comment by obestwalter** [comment]
Hey @dmimat, thanks! That is good to hear. Looking forward to try it out.
